/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package be.nbb.demetra.sssts;

import be.nbb.demetra.sssts.document.SSSTSDocument;
import ec.nbdemetra.ws.WorkspaceFactory;
import ec.nbdemetra.ws.WorkspaceItem;
import ec.nbdemetra.ws.ui.WorkspaceTsTopComponent;
import ec.ui.view.tsprocessing.TsProcessingViewer;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle;
import org.openide.windows.TopComponent;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//be.nbb.nbdemetra.sssts//SSSTS//EN",
autostore = false)
@TopComponent.Description(preferredID = "SSSTSTopComponent",
//iconBase="SET/PATH/TO/ICON/HERE", 
persistenceType = TopComponent.PERSISTENCE_NEVER)
@TopComponent.Registration(mode = "editor", openAtStartup = false)
@ActionID(category = "Seasonal Adjustment", id = "be.nbb.nbdemetra.sssts.SSSTSTopComponent")
@ActionReference(path = "Menu/Statistical methods/Seasonal Adjustment/Single Analysis", position = 1600)
@TopComponent.OpenActionRegistration(displayName = "#CTL_SSSTSAction")
@NbBundle.Messages({
    "CTL_SSSTSAction=Seasonal specific STS",
    "CTL_SSSTSTopComponent=Seasonal specific STS Window",
    "HINT_SSSTSTopComponent=This is a Seasonal specific STS window"
})
public final class SSSTSTopComponent extends WorkspaceTsTopComponent<SSSTSDocument> {

    private static SSSTSDocumentManager manager(){
        return WorkspaceFactory.getInstance().getManager(SSSTSDocumentManager.class);
    }

    public SSSTSTopComponent() {
        super(manager().create(WorkspaceFactory.getInstance().getActiveWorkspace()));
        initDocument();
    }

    public SSSTSTopComponent(WorkspaceItem<SSSTSDocument> doc) {
        super(doc);
        initDocument();
    }

    private void initDocument() {
        initComponents();
        setToolTipText(NbBundle.getMessage(SSSTSTopComponent.class, "HINT_SSSTSTopComponent"));
        setName(getDocument().getDisplayName());
        panel = TsProcessingViewer.create(getDocument().getElement());
        this.add(panel);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(new java.awt.BorderLayout());
    }// </editor-fold>//GEN-END:initComponents

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    @Override
    protected String getContextPath() {
        return SSSTSDocumentManager.CONTEXTPATH;
    }
}
